# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfered_at', models.DateTimeField()),
                ('from_pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_transfers', to='issue_tracker.Pipeline')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='issue_tracker.Issue')),
                ('to_pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_transfers', to='issue_tracker.Pipeline')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue_tracker.Repo'),
        ),
        migrations.AlterUniqueTogether(
            name='transfer',
            unique_together=set([('issue', 'from_pipeline', 'to_pipeline', 'transfered_at')]),
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together=set([('repo', 'number')]),
        ),
    ]
