# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='issue',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='issue_tracker.Repo'),
        ),
        migrations.AddField(
            model_name='duration',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='durations', to='issue_tracker.Issue'),
        ),
        migrations.AddField(
            model_name='duration',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='durations', to='issue_tracker.Pipeline'),
        ),
        migrations.AlterUniqueTogether(
            name='duration',
            unique_together=set([('issue', 'pipeline')]),
        ),
    ]
