# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0002_auto_20170807_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
