# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0004_auto_20170807_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='pipeline_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
