# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0005_pipeline_pipeline_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='from_pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_transfers', to='issue_tracker.Pipeline'),
        ),
    ]
