# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0006_auto_20170807_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineNameMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_name', models.CharField(max_length=255)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue_tracker.Pipeline')),
            ],
        ),
        migrations.AlterField(
            model_name='transfer',
            name='to_pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_transfers', to='issue_tracker.Pipeline'),
        ),
    ]
