# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0007_auto_20170809_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelinenamemapping',
            name='pipeline',
        ),
        migrations.AddField(
            model_name='pipelinenamemapping',
            name='new_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
