# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0008_auto_20170809_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinenamemapping',
            name='repo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='issue_tracker.Repo'),
            preserve_default=False,
        ),
    ]
