# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 13:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0009_pipelinenamemapping_repo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='duration',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='duration',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='duration',
            name='latest_transfer',
        ),
        migrations.RemoveField(
            model_name='duration',
            name='pipeline',
        ),
        migrations.AddField(
            model_name='issue',
            name='durations',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='latest_pipeline_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='latest_transfer_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Duration',
        ),
    ]
