# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 15:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0011_auto_20170810_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='durations',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
