# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0012_auto_20170810_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='is_cycle_time_starter',
            field=models.BooleanField(default=False),
        ),
    ]
