# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 16:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('durations', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('latest_pipeline_name', models.CharField(max_length=255)),
                ('latest_transfer_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pipeline_id', models.CharField(max_length=255, unique=True)),
                ('order', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PipelineNameMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_name', models.CharField(max_length=255)),
                ('new_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfered_at', models.DateTimeField()),
                ('from_pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_transfers', to='boards.Pipeline')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='boards.Issue')),
                ('to_pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_transfers', to='boards.Pipeline')),
            ],
        ),
        migrations.AddField(
            model_name='pipelinenamemapping',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Repo'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Repo'),
        ),
        migrations.AddField(
            model_name='issue',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='boards.Repo'),
        ),
        migrations.AlterUniqueTogether(
            name='transfer',
            unique_together=set([('issue', 'from_pipeline', 'to_pipeline', 'transfered_at')]),
        ),
        migrations.AlterUniqueTogether(
            name='pipeline',
            unique_together=set([('name', 'repo')]),
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together=set([('repo', 'number')]),
        ),
    ]
