# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20171212_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='pipeline_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='pipeline',
            unique_together=set([('pipeline_id', 'repo')]),
        ),
    ]
