# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-12 09:35
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20171212_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), default=list, size=None),
        ),
    ]
